version: "3"
services:
    zalenium:
        image: "dosel/zalenium"
        container_name: zalenium
        hostname: zalenium
        tty: true
        volumes:
            - ' /c/Users/dtung/temp/videos:/home/seluser/videos'
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/usr/local/bin/docker:/usr/local/bin/docker'
        ports:
            - 4444:4444
        command: >
          start --chromeContainers 2
                --firefoxContainers 2
                --maxDockerSeleniumContainers 8
                --screenWidth 800 --screenHeight 600
                --timeZone "America/New_York"
                --videoRecordingEnabled false
                --sauceLabsEnabled false
                --browserStackEnabled false
                --testingBotEnabled false
                --startTunnel false
        environment:
          - HOST_UID
          - HOST_GID
          - SAUCE_USERNAME
          - SAUCE_ACCESS_KEY
          - BROWSER_STACK_USER
          - BROWSER_STACK_KEY
          - TESTINGBOT_KEY
          - TESTINGBOT_SECRET

    golem-test:
      image: downey/golem:1.0
      ports:
        - "5000:5000"
      depends_on:
        - zalenium
