version: "3"
services:
    zalenium:
        image: "dosel/zalenium"
        container_name: zalenium
        hostname: zalenium
        tty: true
        volumes:
            - '/tmp/videos:/home/seluser/videos'
            - '/var/run/docker.sock:/var/run/docker.sock'
            #- '/usr/local/bin/docker:/usr/local/bin/docker'
        ports:
            - 4444:4444
        command: >
          start --desiredContainers 4
                --maxDockerSeleniumContainers 4
                --maxTestSessions 20
                --screenWidth 1200 --screenHeight 900
                --timeZone "America/New_York"
                --videoRecordingEnabled false
                --sauceLabsEnabled false
                --browserStackEnabled false
                --testingBotEnabled false
                --startTunnel false
        environment:
          - HOST_UID
          - HOST_GID
          - SAUCE_USERNAME
          - SAUCE_ACCESS_KEY
          - BROWSER_STACK_USER
          - BROWSER_STACK_KEY
          - TESTINGBOT_KEY
          - TESTINGBOT_SECRET
        depends_on:
          - selenium
    
    selenium:
        image: elgalu/selenium:latest
        command: echo 0
        restart: "no"      
    
    golem-test:
      image: downey/golem:1.0
      container_name: golem-test
      ports:
        - "5000:5000"
      depends_on:
        - zalenium

